name: OBIS manual
title: OBIS manual
baseurl: "/"
url: "https://manual.obis.org"
permalink: pretty
aux_links:
  "The OBIS manual on GitHub":
    - "//github.com/iobis/manual"
heading_anchors: true
ga_tracking: UA-119617958-2
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: false
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme