on:
  push:
     branches:
       - master
       - E-test

name: renderbook

jobs:
  bookdown:
    name: render
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive texlive-latex-extra
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown","DT","webshot"))'
      - name: Install phantomjs
        run: Rscript -e 'webshot::install_phantomjs()'
      - name: Render Book
        run: Rscript build.R
      - name: Create cname file
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./_book/CNAME"
          FILE_DATA: "manual.obis.org"
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
